"""add phone to candidates

Revision ID: 2d944a7138f6
Revises: a9f5e0c6514b
Create Date: 2026-06-06 16:42:36.984142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d944a7138f6'
down_revision: Union[str, None] = 'a9f5e0c6514b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'phone')
    # ### end Alembic commands ###
